#!/usr/bin/env ruby -KU

$: << "#{File.dirname(__FILE__)}/lib"

require 'rubygems'
require 'shotgun'

Shotgun.start(:port => 3000) do
  response.content = "<html><body>Hello from a block</body></html>"
  response.send
end
